### ISSUE TITLE
Missions with A-4E mod don't load

### ISSUE THREAD

**Issue by docsconz** [UOAF/project-tauntaun#107]
Tried to load a mission with the A-4E-C mod, got this error:

```
2022-02-21 01:27:09.064 [ERROR]  Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 94, in wrapper
  File "tauntaun_live_editor\server\server.py", line 283, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 270, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 224, in load_mission
  File "tauntaun_live_editor\camp.py", line 314, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 376, in load_file
  File "tauntaun_live_editor\dcs\dcs\coalition.py", line 160, in load_from_dict
KeyError: 'A-4E-C'
[2022-02-21 01:27:09,064] ERROR in app: Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 94, in wrapper
  File "tauntaun_live_editor\server\server.py", line 283, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 270, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 224, in load_mission
  File "tauntaun_live_editor\camp.py", line 314, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 376, in load_file
  File "tauntaun_live_editor\dcs\dcs\coalition.py", line 160, in load_from_dict
KeyError: 'A-4E-C
```

maybe this mission uploaded?  It's just a .miz renamed to .zip
[sochi bridge strike case III - Copy.zip](https://github.com/UOAF/project-tauntaun/files/8105482/sochi.bridge.strike.case.III.-.Copy.zip)
'

**Comment by adamdoda** [comment]
Mod aircrafts are not supported (by pydcs), I will try to look for a workaround but won't happen anytime soon.
