### ISSUE TITLE
'wirefence' is not a valid LineStyle

### ISSUE THREAD

**Issue by docsconz** [UOAF/project-tauntaun#108]
Got this error when trying to load the attached mission.  This mission also has the A-4E mod, but looks like there was another error before trying to load the A-4

```
[2022-02-21 01:32:41,425] ERROR in app: Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 94, in wrapper
  File "tauntaun_live_editor\server\server.py", line 283, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 270, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 224, in load_mission
  File "tauntaun_live_editor\camp.py", line 314, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 337, in load_file
  File "tauntaun_live_editor\dcs\dcs\drawing\drawings.py", line 31, in load_from_dict
  File "tauntaun_live_editor\dcs\dcs\drawing\layer.py", line 31, in load_from_dict
  File "tauntaun_live_editor\dcs\dcs\drawing\layer.py", line 62, in load_drawing_from_data
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\enum.py", line 339, in __call__
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\enum.py", line 663, in __new__
ValueError: 'wirefence' is not a valid LineStyle
2022-02-21 01:32:41.425 [ERROR]  Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 94, in wrapper
  File "tauntaun_live_editor\server\server.py", line 283, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 270, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 224, in load_mission
  File "tauntaun_live_editor\camp.py", line 314, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 337, in load_file
  File "tauntaun_live_editor\dcs\dcs\drawing\drawings.py", line 31, in load_from_dict
  File "tauntaun_live_editor\dcs\dcs\drawing\layer.py", line 31, in load_from_dict
  File "tauntaun_live_editor\dcs\dcs\drawing\layer.py", line 62, in load_drawing_from_data
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\enum.py", line 339, in __call__
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\enum.py", line 663, in __new__
ValueError: 'wirefence' is not a valid LineStyle
```
[PG shipping hunt - Copy.zip](https://github.com/UOAF/project-tauntaun/files/8105515/PG.shipping.hunt.-.Copy.zip)
This .zip just needs to be renamed to .miz

**Comment by adamdoda** [comment]
Should be fixed in latest build.
