### ISSUE TITLE
Tauntaun fail to load mission in DCS 2.7

### ISSUE THREAD

**Issue by ScopeUOAF** [UOAF/project-tauntaun#67]
Log as follows (tried to load the same mission twice):

Couldn't detect any installed DCS World version
2021-04-23 00:07:04.211 [INFO ]  --------------------------------------------------
2021-04-23 00:07:04.211 [INFO ]  Tauntaun started.
2021-04-23 00:07:04.257 [INFO ]  Using default mission set in config
2021-04-23 00:07:04.257 [WARNI]  Unable to load default mission, using empty mission!
2021-04-23 00:07:04.257 [DEBUG]  Using proactor: IocpProactor
[2021-04-23 00:07:04 -0000] [6008] [INFO] Running on http://0.0.0.0:8080 (CTRL + C to quit)
2021-04-23 00:07:04.273 [INFO ]  Running on http://0.0.0.0:8080 (CTRL + C to quit)
2021-04-23 00:07:21.113 [DEBUG]  adding ws client   0
2021-04-23 00:07:22.050 [INFO ]  $Client_id: 0, Data: ${"key":"request_session_id","value":{}}
2021-04-23 00:07:38.267 [INFO ]  $Client_id: 0, Data: ${"key":"load_mission","value":"TvT25_OPERATION_MANTIS_CRAWL.miz"}
2021-04-23 00:07:39.250 [DEBUG]  removing ws client 000
2021-04-23 00:07:39.250 [ERROR]  Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 95, in wrapper
  File "tauntaun_live_editor\server\server.py", line 284, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 271, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 225, in load_mission
  File "tauntaun_live_editor\camp.py", line 345, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 359, in load_file
  File "tauntaun_live_editor\dcs\dcs\forcedoptions.py", line 80, in load_from_dict
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 339, in __call__
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 662, in __new__
ValueError: 4 is not a valid Labels
[2021-04-23 00:07:39,250] ERROR in app: Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 95, in wrapper
  File "tauntaun_live_editor\server\server.py", line 284, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 271, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 225, in load_mission
  File "tauntaun_live_editor\camp.py", line 345, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 359, in load_file
  File "tauntaun_live_editor\dcs\dcs\forcedoptions.py", line 80, in load_from_dict
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 339, in __call__
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 662, in __new__
ValueError: 4 is not a valid Labels
2021-04-23 00:07:42.450 [DEBUG]  adding ws client   1
2021-04-23 00:07:43.590 [INFO ]  $Client_id: 1, Data: ${"key":"request_session_id","value":{}}
2021-04-23 00:09:00.000 [INFO ]  $Client_id: 1, Data: ${"key":"load_mission","value":"TvT25_OPERATION_MANTIS_CRAWL.miz"}
2021-04-23 00:09:00.953 [DEBUG]  removing ws client 001
2021-04-23 00:09:00.953 [ERROR]  Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 95, in wrapper
  File "tauntaun_live_editor\server\server.py", line 284, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 271, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 225, in load_mission
  File "tauntaun_live_editor\camp.py", line 345, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 359, in load_file
  File "tauntaun_live_editor\dcs\dcs\forcedoptions.py", line 80, in load_from_dict
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 339, in __call__
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 662, in __new__
ValueError: 4 is not a valid Labels
[2021-04-23 00:09:00,953] ERROR in app: Exception on websocket /ws/message
Traceback (most recent call last):
  File "lib\site-packages\quart\app.py", line 1937, in handle_websocket
  File "lib\site-packages\quart\app.py", line 1959, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 1076, in handle_user_exception
  File "lib\site-packages\quart\app.py", line 1957, in full_dispatch_websocket
  File "lib\site-packages\quart\app.py", line 2002, in dispatch_websocket
  File "tauntaun_live_editor\server\server.py", line 95, in wrapper
  File "tauntaun_live_editor\server\server.py", line 284, in client_update_ws
  File "tauntaun_live_editor\server\server.py", line 271, in process_message_request
  File "tauntaun_live_editor\server\server.py", line 225, in load_mission
  File "tauntaun_live_editor\camp.py", line 345, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 359, in load_file
  File "tauntaun_live_editor\dcs\dcs\forcedoptions.py", line 80, in load_from_dict
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 339, in __call__
  File "C:\hostedtoolcache\windows\Python\3.8.9\x64\lib\enum.py", line 662, in __new__
ValueError: 4 is not a valid Labels
2021-04-23 00:09:04.404 [DEBUG]  adding ws client   2
2021-04-23 00:09:05.388 [INFO ]  $Client_id: 2, Data: ${"key":"request_session_id","value":{}}

**Comment by adamdoda** [comment]
Fixed in af89829c57f18d472ffbff53244dc36b7ff58347.
