### ISSUE TITLE
Embarking bug

### ISSUE THREAD

**Issue by Heater711** [UOAF/project-tauntaun#93]
2021-11-15 09:34:53.141 [INFO ]  Tauntaun started.
2021-11-15 09:34:53.141 [INFO ]  Using default mission set in config
2021-11-15 09:34:55.293 [ERROR]  Got exception on main handler
Traceback (most recent call last):
  File "tauntaun_live_editor\camp.py", line 381, in main
  File "tauntaun_live_editor\camp.py", line 314, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 370, in load_file
    self.weather.load_from_dict(imp_weather)
  File "tauntaun_live_editor\dcs\dcs\coalition.py", line 190, in load_from_dict
    Coalition._import_moving_point(mission, helicopter_group, pgroup)
  File "tauntaun_live_editor\dcs\dcs\coalition.py", line 41, in _import_moving_point
    point.load_from_dict(imp_point, mission.translation)
  File "tauntaun_live_editor\dcs\dcs\point.py", line 152, in load_from_dict
    self.tasks.append(task._create_from_dict(d["task"]["params"]["tasks"][t]))
  File "tauntaun_live_editor\dcs\dcs\task.py", line 30, in _create_from_dict
    t = tasks_map[_id].create_from_dict(d)
KeyError: 'Disembarking'
2021-11-15 09:34:55.293 [INFO ]  Tauntaun stopped gracefully.
2021-11-15 09:34:55.293 [INFO ]  --------------------------------------------------

**Comment by adamdoda** [comment]
Fixed in https://github.com/UOAF/project-tauntaun/actions/runs/1463802845

**Comment by adamdoda** [comment]
No comment
