### ISSUE TITLE
AttackUnit Bug

### ISSUE THREAD

**Issue by Heater711** [UOAF/project-tauntaun#95]
2021-11-15 22:45:36.115 [INFO ]  Tauntaun started.
2021-11-15 22:45:36.120 [INFO ]  Using default mission set in config
2021-11-15 22:45:38.677 [ERROR]  Got exception on main handler
Traceback (most recent call last):
  File "tauntaun_live_editor\camp.py", line 381, in main
  File "tauntaun_live_editor\camp.py", line 314, in load_mission
  File "tauntaun_live_editor\dcs\dcs\mission.py", line 376, in load_file
  File "tauntaun_live_editor\dcs\dcs\coalition.py", line 152, in load_from_dict
  File "tauntaun_live_editor\dcs\dcs\coalition.py", line 41, in _import_moving_point
  File "tauntaun_live_editor\dcs\dcs\point.py", line 152, in load_from_dict
  File "tauntaun_live_editor\dcs\dcs\task.py", line 30, in _create_from_dict
KeyError: 'AttackUnit'
2021-11-15 22:45:38.680 [INFO ]  Tauntaun stopped gracefully.
2021-11-15 22:45:38.680 [INFO ]  --------------------------------------------------

**Comment by adamdoda** [comment]
https://github.com/UOAF/project-tauntaun/actions/runs/1468535939
